### PR TITLE
Redirect on 404

### LINKED ISSUE #31: Middleware doesn’t appear to be compatible with django flatpages
This middleware doesn’t redirect to login if the response is a 404.

I think this means the middleware is not compatible with [django flatpages](https://docs.djangoproject.com/en/3.1/ref/contrib/flatpages/) – specifically the [FlatpageFallbackMiddleware](https://docs.djangoproject.com/en/3.1/ref/contrib/flatpages/#django.contrib.flatpages.middleware.FlatpageFallbackMiddleware), which relies on intercepting 404 responses. If someone uses that app with this, pages that should be behind a login may accidentally be exposed.

It could _arguably_ also be considered a security issue, since responding to some requests with a 404 leaks information about which routes behind the login are valid.

---

EDIT: Sorry, I should add: Many thanks for making this! It is great. I’ve sent a PR in an attempt to fix this issue.

### PR DESCRIPTION
**Pull request by andylolz**
There’s a little bit of refactoring in here, but I’ve tried to split it out into separate commits.

Fixes #31.

Do let me know if there’s anything I can change here, or anything I can help with. Thanks!

### CODE REVIEW

**Comment by andylolz** [comment]
Hmm… Tests pass locally, but the build fails here. It looks like it’s a coveralls token problem.

**Comment by CleitonDeLima** [comment]
Rebase this PR with master.

After that i can include this PR in a new version

**Comment by andylolz** [comment]
> Rebase this PR with master.

Okay – done. Though it looks as though there is still some coveralls problem…

**Comment by CleitonDeLima** [comment]
> Okay – done. Though it looks as though there is still some coveralls problem…

I remembered what it might be, the branch is in your account, coveralls I think it only checks my token.

**Comment by andylolz** [comment]
> coveralls I think it only checks my token

Looks like you were quite right!

Thanks so much for reviewing and merging this so quickly, and thanks again for creating and maintaining this project 🙏

**Pull request merged**
